spring:
  application:
    name: route-demo
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234567a
    url: jdbc:mysql://127.0.0.1:3306/code_demo?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai


route:
  default-key: default
  strict-mode: false
  mappings:
    beta_fault:
      module: faultDetail
      suffix: /betaSuffix
      description: Beta-env
      enabled: true


    comm_fault:
      module: faultDetail
      suffix: /commSuffix
      description: Comm-env
      enabled: true

    beta_other_app:
      module: otherAppFaultDetail
      suffix: /betaSuffix
      description: Beta-other-app
      enabled: true

    comm_other_app:
      module: otherAppFaultDetail
      suffix: /commSuffix
      description: Comm-other-app
      enabled: true

    default:
      module: faultDetail
      suffix: /betaSuffix
      description: default
      enabled: true
